In [1]:
import numpy as np

# Datatypes and attributes

numpy's main datatype is   
ndarray = n-dimentional

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.3,3.2],
               [1.0,2.9,0]])
a2

array([[1. , 2.3, 3.2],
       [1. , 2.9, 0. ]])

In [7]:
a3 = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                 [[10,11,12],
                  [13,14,15],
                  [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

check the numpy-array.jpg to view in 3D

axis 0 = rows,
axis 1 = cols,
axis n = depth

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [11]:
a3.shape
# this bascically means the R*C*Depth

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim
# this tells us the dimension of each 

(1, 2, 3)

In [15]:
a1.dtype, a2.dtype, a3.dtype
# types of values stored, it has to be hetrogenous

(dtype('int64'), dtype('float64'), dtype('int64'))

In [16]:
a1.size, a2.size, a3.size
# number of elements in each array

(3, 6, 18)

In [19]:
type(a1), type(a2), type(a3)
# all are of the same type regardless of their dimension

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [23]:
# create a dataframe from a numpy array
import pandas as pd

In [24]:
df = pd.DataFrame(a2)
df

,0,1,2
0,1.0,2.3,3.2
1,1.0,2.9,0.0
