In [1]:
import numpy as np

# Datatypes and attributes

numpy's main datatype is   
ndarray = n-dimentional

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.3,3.2],
               [1.0,2.9,0]])
a2

array([[1. , 2.3, 3.2],
       [1. , 2.9, 0. ]])

In [5]:
a3 = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                 [[10,11,12],
                  [13,14,15],
                  [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

check the numpy-array.jpg to view in 3D

axis 0 = rows,
axis 1 = cols,
axis n = depth

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape
# this bascically means the R*C*Depth

(2, 3, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim
# this tells us the dimension of each 

(1, 2, 3)

In [10]:
a1.dtype, a2.dtype, a3.dtype
# types of values stored, it has to be hetrogenous

(dtype('int64'), dtype('float64'), dtype('int64'))

In [11]:
a1.size, a2.size, a3.size
# number of elements in each array

(3, 6, 18)

In [12]:
type(a1), type(a2), type(a3)
# all are of the same type regardless of their dimension

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [13]:
# create a dataframe from a numpy array
import pandas as pd

In [14]:
df = pd.DataFrame(a2)
df

,0,1,2
0,1.0,2.3,3.2
1,1.0,2.9,0.0


## Creating numpy arrays

press shift+tab to see what a funciton does

In [16]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [18]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array = np.arange(0,10,1) # start,stop,step
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[4, 0, 6, 2, 3],
       [9, 7, 1, 7, 6],
       [4, 6, 7, 0, 5]], dtype=int32)

In [28]:
random_array.size

15

In [29]:
random_array.shape

(3, 5)

In [31]:
random_array_2 = np.random.random((5,3)) 
random_array_2

array([[0.94609892, 0.88281901, 0.515438  ],
       [0.72451843, 0.70288055, 0.19118073],
       [0.08120286, 0.25236263, 0.62136531],
       [0.80757335, 0.42619186, 0.40559118],
       [0.78072612, 0.04949092, 0.05587414]])

In [32]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.63876999, 0.68958341, 0.19889034],
       [0.82337074, 0.87657014, 0.61559873],
       [0.86837569, 0.27483456, 0.47477047],
       [0.54053515, 0.19192162, 0.03158661],
       [0.00905891, 0.05478333, 0.54393283]])

In [41]:
# pseudo-random numbers :- random numbers are not actually random
# lets say we want to get to share our notebook to someone
# and they should get the same random numbers to replicate the result 
# this is where we use random seed 
np.random.seed(seed=0) # the numbers are now fixed, tied to the seed = 0, this seed can be any int
# works with every random function
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)