In [1]:
import numpy as np

# Datatypes and attributes

numpy's main datatype is   
ndarray = n-dimentional

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.3,3.2],
               [1.0,2.9,0]])
a2

array([[1. , 2.3, 3.2],
       [1. , 2.9, 0. ]])

In [5]:
a3 = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                 [[10,11,12],
                  [13,14,15],
                  [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

check the numpy-array.jpg to view in 3D

axis 0 = rows,
axis 1 = cols,
axis n = depth

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape
# this bascically means the R*C*Depth

(2, 3, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim
# this tells us the dimension of each 

(1, 2, 3)

In [10]:
a1.dtype, a2.dtype, a3.dtype
# types of values stored, it has to be hetrogenous

(dtype('int64'), dtype('float64'), dtype('int64'))

In [11]:
a1.size, a2.size, a3.size
# number of elements in each array

(3, 6, 18)

In [12]:
type(a1), type(a2), type(a3)
# all are of the same type regardless of their dimension

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [13]:
# create a dataframe from a numpy array
import pandas as pd

In [14]:
df = pd.DataFrame(a2)
df

,0,1,2
0,1.0,2.3,3.2
1,1.0,2.9,0.0


## Creating numpy arrays

press shift+tab to see what a funciton does

In [15]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
type(ones)

numpy.ndarray

In [18]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
range_array = np.arange(0,10,1) # start,stop,step
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[3, 7, 1, 8, 7],
       [8, 2, 8, 7, 0],
       [9, 2, 6, 1, 4]], dtype=int32)

In [21]:
random_array.size

15

In [22]:
random_array.shape

(3, 5)

In [23]:
random_array_2 = np.random.random((5,3)) 
random_array_2

array([[0.03101952, 0.72965593, 0.97716527],
       [0.38126434, 0.34499399, 0.58381129],
       [0.69096795, 0.8520541 , 0.58301865],
       [0.90462587, 0.22663194, 0.35064679],
       [0.61363271, 0.6989126 , 0.68594495]])

In [24]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.36637787, 0.84641607, 0.68420471],
       [0.17652527, 0.31868136, 0.34605611],
       [0.2483391 , 0.39935969, 0.01027059],
       [0.19641435, 0.65786846, 0.83485177],
       [0.42735505, 0.01220342, 0.06497193]])

In [25]:
# pseudo-random numbers :- random numbers are not actually random
# lets say we want to get to share our notebook to someone
# and they should get the same random numbers to replicate the result 
# this is where we use random seed 
np.random.seed(seed=0) # the numbers are now fixed, tied to the seed = 0, this seed can be any int
# works with every random function
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

## Viewing arrays and matrices

In [26]:
# finding unique numbers in an array
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [27]:
a1[0]

np.int64(1)

In [28]:
a2[0]

array([1. , 2.3, 3.2])

In [29]:
a2[0][1]

np.float64(2.3)

In [30]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
a4 = np.random.randint(10, size=(2,3,4))
a4
# start looking from right to left i.e. 4 elements in the innnermost bracket, then 3 , then 2

array([[[6, 7, 7, 8],
        [1, 5, 9, 8],
        [9, 4, 3, 0]],

       [[3, 5, 0, 2],
        [3, 8, 1, 3],
        [3, 3, 7, 0]]], dtype=int32)

In [32]:
a4[1][0]

array([3, 5, 0, 2], dtype=int32)

we can also use slicing here as in python lists

## Manipulating and comparing arrays

Arithmetic

In [33]:
a1

array([1, 2, 3])

In [34]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [36]:
a1+ones
# adds each index with its corresponding index

array([2., 3., 4.])

In [37]:
a1-ones

array([0., 1., 2.])

In [38]:
a2

array([[1. , 2.3, 3.2],
       [1. , 2.9, 0. ]])

In [40]:
a1

array([1, 2, 3])

In [41]:
a1*a2

array([[1. , 4.6, 9.6],
       [1. , 5.8, 0. ]])

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [43]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

search for numpy broadcasting, how to reshape an array 

In [44]:
a1/ones

array([1., 2., 3.])

In [47]:
a2//a1
# floor division :- removes the decimals

array([[1., 1., 1.],
       [1., 1., 0.]])

In [48]:
a2/a1

array([[1.        , 1.15      , 1.06666667],
       [1.        , 1.45      , 0.        ]])

In [49]:
a2 ** 2
# power 

array([[ 1.  ,  5.29, 10.24],
       [ 1.  ,  8.41,  0.  ]])

In [50]:
a2

array([[1. , 2.3, 3.2],
       [1. , 2.9, 0. ]])

In [51]:
np.square(a2)

array([[ 1.  ,  5.29, 10.24],
       [ 1.  ,  8.41,  0.  ]])

numpy has functions for all these arithimatic functions

In [53]:
np.mod(a2,ones)

array([[0. , 0.3, 0.2],
       [0. , 0.9, 0. ]])